import { Dosis } from "next/font/google";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Script from "next/script";
import Loader from "@/components/loader";

// css
import "../styles/css/bootstrap.min.css";
import "swiper/css";
import "swiper/css/pagination";
import "../styles/css/daterangepicker.min.css";
import "../styles/css/bootstrap-datetimepicker.min.css";
import "../styles/css/shortcodes.css";
import "../styles/css/style.css";
import "../styles/css/responsive.css";

const dosis = Dosis({ subsets: ["latin"] });

export const metadata = {
  title: "Prodrive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="/revolution/js/jquery.min.js" />
        <Script src="/js/waypoints.min.js" />
        <Script src="/js/owl.carousel.js" />
        <Script src="/revolution/js/jquery.themepunch.tools.min.js" />
        <Script src="/revolution/js/jquery.themepunch.revolution.min.js" />
        <Script src="/revolution/js/slider.js" />
        <Script src="/js/template.js" />
        <Script src="/js/moment.min.js" />
        <Script src="/js/jquery.daterangepicker.js" />
        <Script src="/js/waves.min.js" />
        <Script src="/js/bootstrap-datetimepicker.js" />
        <Script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBtRmXKclfDp20TvfQnpgXSDPjut14x5wk&region=GB" />

        {/* <link rel="stylesheet" href="/src/styles/css/daterangepicker.min.css" /> */}
        <link rel="stylesheet" href="/revolution/css/layers.css" />
        <link rel="stylesheet" href="/revolution/css/settings.css" />
      </head>
      <body className={dosis.className}>
        <div className="layout-theme">
          {/* {loading && (
            <div id="loading-overlay">
              <div className="loader"></div>
            </div>
          )} */}

          <Loader />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
