export const vehicleData = [
  {
    id: 1,
    img: "/images/booking/car-01.jpg",
    title: "Economy Premium",
    subtitle: "Mercedes-Benz E-Class, BMW 5 Series, Cadillac XTS, or similar",
    desc: "A favorite for business professionals and frequent travelers, Prodirve Economy Premiun vehicles are available in all of our cities worldwide.",
    author: "Max . 3",
    mail: "Max . 2",
    price: "49",
  },
  {
    id: 2,
    img: "/images/booking/car-02.jpg",
    title: "Business Class",
    subtitle: "Mercedes-Benz E-Class, BMW 5 Series, Cadillac XTS, or similar",
    desc: "A favorite for business professionals and frequent travelers, Prodirve Economy Premiun vehicles are available in all of our cities worldwide.",
    author: "Max . 3",
    mail: "Max . 2",
    price: "99",
  },
  {
    id: 3,
    img: "/images/booking/car-03.png",
    title: "Business Van",
    subtitle: "Mercedes-Benz E-Class, BMW 5 Series, Cadillac XTS, or similar",
    desc: "A favorite for business professionals and frequent travelers, Prodirve Economy Premiun vehicles are available in all of our cities worldwide.",
    author: "Max . 3",
    mail: "Max . 2",
    price: "189",
  },
  {
    id: 4,
    img: "/images/booking/car-04.jpg",
    title: "First Class",
    subtitle: "Mercedes-Benz E-Class, BMW 5 Series, Cadillac XTS, or similar",
    desc: "A favorite for business professionals and frequent travelers, Prodirve Economy Premiun vehicles are available in all of our cities worldwide.",
    author: "Max . 3",
    mail: "Max . 2",
    price: "159",
  },
];
